#!/bin/bash

export EXPYRE_PYTEST_SYSTEMS='(tin|mustang)'

echo  "GIT VERSION " $( git describe --always --tags --dirty ) > pytest_complete_test.out 
echo "" >> pytest_complete_test.out 

rm -rf $HOME/pytest_expyre
ssh $KMUSTANG rm -rf pytest_expyre_rundir_mustang
pytest --clean --basetemp $HOME/pytest_expyre >> pytest_complete_test.out 2>&1

l=`egrep 'passed.*xfailed' pytest_complete_test.out`

echo $l | grep -q -v 'skipped'
if [ $? != 0 ]; then
    echo "Unexpected number skipped not 0 '$l'" 1>&2
    exit 1
fi
echo $l | grep -q ' 22 passed'
if [ $? != 0 ]; then
    echo "Unexpected number passed not 22 '$l'" 1>&2
    exit 1
fi
echo $l | grep -q ' 1 xfailed'
if [ $? != 0 ]; then
    echo "Unexpected number xfailed not 1 '$l'" 1>&2
    exit 1
fi
